### ISSUE TITLE
Opencms does not work on initial setup

### ISSUE THREAD

**Issue by chan-alex** [mrigeshpriyadarshi/aws_opencms#1]
Hi,
After running all the ansible script, the OpenCMS is installed but does not appear to be 100% operational. See attached pic
![screen shot 2017-06-02 at 3 54 42 pm](https://cloud.githubusercontent.com/assets/112162/26716523/590aa77c-47ac-11e7-8f17-102f3eb5a63b.png)

OpenCMS appear to be installed but the web instance does not appear to show the main page correctly.

**Comment by mrigeshpriyadarshi** [comment]
Looking into it.

**Comment by mrigeshpriyadarshi** [comment]
Fixed the issue as it was due to delay of Auto setup wizard.

<img width="1052" alt="screen shot 2017-06-05 at 3 19 28 pm" src="https://cloud.githubusercontent.com/assets/3006479/26774363/7d6a371a-4a02-11e7-8ee5-9adac1677fde.png">
