### ISSUE TITLE
App and DB in public subnet

### ISSUE THREAD

**Issue by chan-alex** [mrigeshpriyadarshi/aws_opencms#2]
The app and db instances are directly accessible from the internet. This invites bot scanning and give an opening for hacking attacks. It is probably a better idea to place the app and db instances into private subnets.

**Comment by chan-alex** [comment]
Just an observation. Not need to follow up on this.

**Comment by mrigeshpriyadarshi** [comment]
Yes its in public subnet as Private subnet would needed a NAT gateway and bastion host to connect to internet/SSH. Wanted to save there. :)

Anyhow all ports on those instances are blocked, except SSH port.
